// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kolobok-kelbek/go-example-service/infra"
)

// Injectors from wire.go:

func Init() *infra.App {
	app := infra.NewApp()
	return app
}
